[package]
name = "ncm-play"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"

gstreamer = "0.23.3"
gstreamer-play = "0.23.2"

log = "0.4.22"

ncm-client = { path = "../ncm-client" }

rand = "0.8.5"

tokio = "1.41.1"